/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class www_ql_com_okhttputils_Natives */

#ifndef _Included_www_ql_com_okhttputils_Natives
#define _Included_www_ql_com_okhttputils_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     www_ql_com_okhttputils_Natives
 * Method:    LiMain
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_www_ql_com_okhttputils_Natives_LiMain
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
